name: Publish Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract version (from git tag or fallback to commit SHA)
        id: version
        run: |
          # Попробуем взять git tag, если есть
          VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push image
        run: |
          VERSION=${{ steps.version.outputs.VERSION }}
          IMAGE=ghcr.io/${{ github.repository_owner }}/chatwave-web

          echo "Building image: $IMAGE:latest and $IMAGE:$VERSION"

          docker buildx build --platform linux/amd64,linux/arm64 \
            -t $IMAGE:latest \
            -t $IMAGE:$VERSION \
            --push .
