name: Publish Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract version from package.json
        id: version
        run: |
          echo "VERSION=$(jq -r .version package.json)" >> "$GITHUB_OUTPUT"

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image with version
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/chatwave-web
          VERSION=${{ steps.version.outputs.VERSION }}

          docker buildx build --platform linux/amd64,linux/arm64 \
            -t $IMAGE:latest \
            -t $IMAGE:$VERSION \
            --push .
